import { CCClasses, init, SocketIOClient } from '@buerli.io/classcad'
import { elements } from '@buerli.io/react'
import {
  Boolean as BooleanPlg,
  BoundingBoxInfo,
  Box,
  Chamfer,
  CircularPattern,
  CompositeCurve,
  Cone,
  Cylinder,
  Cylindrical,
  Expressions,
  Extrusion,
  EntityDeletion,
  Fastened,
  FastenedOrigin,
  Fillet,
  Import,
  LinearPattern,
  Measure,
  Parallel,
  Planar,
  ProductManagement,
  Revolute,
  Revolve,
  Rotate,
  Sketch,
  Slice,
  SliceBySheet,
  Slider,
  Sphere,
  TransformByCsys,
  Translate,
  WorkAxis,
  WorkCSys,
  WorkPlane,
  WorkPoint,
} from '@buerli.io/react-cad'

const CCSERVERURL = 'ws://localhost:8182'

export const initBuerli = () => {
  console.info('initBuerli')

  init(id => new SocketIOClient(CCSERVERURL, id), {
    theme: {
      primary: '#e36b7c',
      secondary: '#fcc7cb',
      dark: '#a0a0a0',
      highlightedGeom: '#e36b7c',
      hoveredGeom: '#40a9ff',
    },
    config: {
      geometry: {
        disabled: false,
        edges: { hidden: false, opacity: 1.0, color: 'black' },
        points: { hidden: true, opacity: 1.0, color: 'black' },
        // meshes: { hidden: false, opacity: 1.0, wireframe: false },
      },
    },
    elements,
    globalPlugins: [Measure, BoundingBoxInfo, Expressions, ProductManagement],
    plugins: {
      [CCClasses.CCSketch]: Sketch,
      [CCClasses.CCExtrusion]: Extrusion,
      [CCClasses.CCChamfer]: Chamfer,
      [CCClasses.CCConstantRadiusFillet]: Fillet,
      [CCClasses.CCUnion]: BooleanPlg,
      [CCClasses.CCWorkAxis]: WorkAxis,
      [CCClasses.CCWorkPlane]: WorkPlane,
      [CCClasses.CCWorkPoint]: WorkPoint,
      [CCClasses.CCRevolve]: Revolve,
      [CCClasses.CCBox]: Box,
      [CCClasses.CCSphere]: Sphere,
      [CCClasses.CCCylinder]: Cylinder,
      [CCClasses.CCCone]: Cone,
      [CCClasses.CCWorkCSys]: WorkCSys,
      [CCClasses.CCIntersection]: BooleanPlg,
      [CCClasses.CCSubtraction]: BooleanPlg,
      [CCClasses.CCSlice]: Slice,
      [CCClasses.CCSliceBySheet]: SliceBySheet,
      [CCClasses.CCLinearPattern]: LinearPattern,
      [CCClasses.CCCircularPattern]: CircularPattern,
      [CCClasses.CCCompositeCurve]: CompositeCurve,
      [CCClasses.CCTransformationByCSys]: TransformByCsys,
      [CCClasses.CCTranslation]: Translate,
      [CCClasses.CCRotation]: Rotate,
      [CCClasses.CCFastenedOriginConstraint]: FastenedOrigin,
      [CCClasses.CCFastenedConstraint]: Fastened,
      [CCClasses.CCSliderConstraint]: Slider,
      [CCClasses.CCRevoluteConstraint]: Revolute,
      [CCClasses.CCCylindricalConstraint]: Cylindrical,
      [CCClasses.CCPlanarConstraint]: Planar,
      [CCClasses.CCParallelConstraint]: Parallel,
      [CCClasses.CCImport]: Import,
      [CCClasses.CCEntityDeletion]: EntityDeletion,
    },
  })
}
