/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Buerligons",
  "tagline": "Cad for the web",
  "url": "https://buerligons.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.png",
  "organizationName": "awv-informatik",
  "projectName": "buerligons",
  "themeConfig": {
    "footer": {
      "style": "light",
      "links": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#e4f0fb",
          "backgroundColor": "#252b37"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#a6accd"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#d0679d"
            }
          },
          {
            "types": [
              "punctuation",
              "property",
              "tag",
              "constant",
              "symbol"
            ],
            "style": {
              "color": "#e4f0fb"
            }
          },
          {
            "types": [
              "atrule",
              "function",
              "class-name",
              "boolean",
              "number",
              "selector",
              "attr-value",
              "string",
              "char",
              "builtin",
              "inserted"
            ],
            "style": {
              "color": "#5de4c7"
            }
          },
          {
            "types": [
              "attr-name",
              "operator",
              "entity",
              "url",
              "variable"
            ],
            "style": {
              "color": "#add7ff"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "add7ff"
            }
          },
          {
            "types": [
              "regex",
              "important"
            ],
            "style": {
              "color": "#fffac2"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "Buerligons",
      "logo": {
        "alt": "AWV Logo",
        "src": "favicon.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "href": "https://x.com/buerli_io",
          "label": "X",
          "position": "right"
        },
        {
          "href": "https://discord.gg/MEbR7xyPMS",
          "label": "Discord",
          "position": "right"
        },
        {
          "href": "https://github.com/awv-informatik",
          "label": "GitHub",
          "position": "right"
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/ph/dev/buerli/buerligons.io/sidebars.js"
        },
        "blog": false,
        "theme": {
          "customCss": "/Users/ph/dev/buerli/buerligons.io/src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    [
      "/Users/ph/dev/buerli/buerligons.io/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "indexPages": true,
        "docsRouteBasePath": "/docs",
        "hashed": true,
        "language": [
          "en"
        ],
        "highlightSearchTermsOnTargetPage": false,
        "searchResultContextMaxLength": 50,
        "searchResultLimits": 8,
        "searchBarShortcut": true,
        "searchBarShortcutHint": true
      }
    ]
  ],
  "plugins": [
    [
      "./src/plugins/tailwind-config.js",
      {}
    ],
    "./src/plugins/fixesm.js",
    [
      "docusaurus-plugin-module-alias",
      {
        "alias": {
          "react": "/Users/ph/dev/buerli/buerligons.io/node_modules/react",
          "react-dom": "/Users/ph/dev/buerli/buerligons.io/node_modules/react-dom",
          "styled-components": "/Users/ph/dev/buerli/buerligons.io/node_modules/styled-components"
        }
      }
    ],
    [
      "ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
